version: '3.2'
services:
  sql-server-studybuddydb:
    container_name: sql-server-studybuddydb
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Password_4_StudyBuddy_&'
      ACCEPT_EULA: 'Y'
